### ISSUE TITLE
App run time erro

### ISSUE THREAD

**Issue by yantaodehaoma** [KagayamaKaede/ShadowsocksRDroid#2]
It seems ,that you forgot to update some files.

 Caused by: java.lang.ClassCastException: java.util.HashMap cannot be cast to com.proxy.shadowsocksr.items.SSProfile
            at com.proxy.shadowsocksr.fragment.PrefFragment.loadCurrentPref(PrefFragment.java:175)
            at com.proxy.shadowsocksr.fragment.PrefFragment.onResume(PrefFragment.java:62)
            at android.app.Fragment.performResume(Fragment.java:1743)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:924)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)

**Comment by KagayamaKaede** [comment]
You not clear old app data?
I changed storage data format,so need clear old data.

**Comment by KagayamaKaede** [comment]
@yantaodehaoma If issue is solved,please close this issue,Thank you :)
